schematics:
  EXAMPLE_SCHEMATIC:
    schematic: "hut.schem" # schematic file name with extension
    world: world
    location1: 1000, 60, 1000
    location2: -1000, 200, -1000
    type: GROUND # UNDERGROUND | GROUND | SKY
    unbreakable: true
    spawn: 1 # amount of structures to spawn at a time
    interval: 1 # in days
    despawn: 1 # in days
    tries: 10
    mobs:
      - ZOMBIE:10
    mythic-mobs:
      - SkeletalKnight:5
    command-on-spawn:
      - "broadcast &aA structure just spawned in %world% at %x% %y% %z%"
    command-on-despawn:
      - "broadcast &aA structure just despawned"
    checks:
      town: true # Stops structure from spawning in a town
      water: false # Stops structure from spawning in water
      lava: false # Stops structure from spawning in lava
      has-blocks: # Stops structure from spawning if the specified blocks are not near the spawning location
        - GRASS_BLOCK
      has-not-blocks: # Stops structure from spawning if the specified blocks are near the spawning location
        - SAND