name: MortisStructures
version: '1.0'
main: me.none030.mortisstructures.MortisStructures
api-version: 1.13
softdepend:
  - Towny
  - MythicMobs
depend:
  - WorldEdit
commands:
  structures:
    aliases: mortisstructures